Feature/create azure function for image processing
open-campaign-logger/world-map pull request #14
Opened 2021-04-19 21:14 UTC by talktocory

Hi Jochen,

The world-map Azure function is ready for review.  

Some notes:

- I had to split it up into three projects because the UI and the Function both needed access to the same core services (blob, table, queue).
- It turns out the Azure Functions support DI so I was able to leverage the exact same services in both the UI and the Function.
- Azure Functions only support  up to .Net core 3.1 at this time.  Project .Net levels are as follows:
  - CampaignKit.WorldMap.Core: .Net Core 3.1
  - CampaignKit.WorldMap.UI: .Net 5.0
  - CampaignKit.WorldMap.Function: .Net Core 3.1
  - CampaignKit.WorldMap.Tests: .Net 5.0
- You will need to setup an Azure Queue named 'worldmapqueue'.
- There is no longer a .Net background process running in the UI app.  This was recreated as a DI service named MapProcessingService.
- New process works like this
  - DefaultMapRepository creates a message in 'worldmapqueue' when a new map is added to the 'worldmapmaps' table.
  - The new Azure Function is bound to the queue.  Writing to the queue kicks off the function.
  - The function calls the MapProcessingService with the mapId and the service creates the tiles.

2021-04-22 06:08 UTC, JochenLinnemann commented
> * New process works like this
>   
>   * DefaultMapRepository creates a message in 'worldmapqueue' when a new map is added to the 'worldmapmaps' table.
>   * The new Azure Function is bound to the queue.  Writing to the queue kicks off the function.
>   * The function calls the MapProcessingService with the mapId and the service creates the tiles.

Is this fast enough? A function can only run for that many minutes. Shouldn't we schedule actual tiles as function calls instead of the whole tile creation process?

2021-04-22 06:23 UTC, JochenLinnemann requested changes

2021-04-22 06:23 UTC, JochenLinnemann commented on src/CampaignKit.WorldMap.Core/Services/IProgressService.cs
>      using System.Threading.Tasks;
Can you move all usings in all files outside the namespace, please?

2021-04-22 06:23 UTC, JochenLinnemann commented on src/CampaignKit.WorldMap.Function/ProcessMapTrigger.cs
> +        public async Task Run([QueueTrigger("worldmapqueue", Connection = "")]string myQueueItem)
The queuing service add the id as b64-encoded byte array to the queue - are we sure this automatically decoded and turned into the original UTF8 string here?

2021-04-22 12:08 UTC, talktocory commented
> Is this fast enough? A function can only run for that many minutes. Shouldn't we schedule actual tiles as function calls instead of the whole tile creation process?

I had considered both approaches.  Originally I wanted to do one trigger per tile but that would mean some rewriting of the TileService.  Currently the TileService (now called DefaultMapProcessingService) creates map tiles by zoom level.  It does the following:
- Looks for unprocessed tiles
- Groups them by zoom  level
- Creates a zoom level base image
- Creates the required tiles from that zoom level base image

This doesn't quite support the one-trigger-per-tile approach.  It doesn't currently seem to be an issue because the largest image you can upload to World Map is 10MB which the function seems to handle pretty easily.  

Happy to break this piece up into multiple triggers if you want a more robust solution.  Let me know if you want me to make the changes.

2021-04-22 12:12 UTC, JochenLinnemann commented
> > Is this fast enough? A function can only run for that many minutes. Shouldn't we schedule actual tiles as function calls instead of the whole tile creation process?
> 
> I had considered both approaches. Originally I wanted to do one trigger per tile but that would mean some rewriting of the TileService. Currently the TileService (now called DefaultMapProcessingService) creates map tiles by zoom level. It does the following:
> 
> * Looks for unprocessed tiles
> * Groups them by zoom  level
> * Creates a zoom level base image
> * Creates the required tiles from that zoom level base image
> 
> This doesn't quite support the one-trigger-per-tile approach. It doesn't currently seem to be an issue because the largest image you can upload to World Map is 10MB which the function seems to handle pretty easily.
> 
> Happy to break this piece up into multiple triggers if you want a more robust solution. Let me know if you want me to make the changes.

You are right, let's first test this before investing more work.

2021-04-22 12:12 UTC, talktocory commented
I see that the unit tests project is now failing to build in the pipeline.  I'll look into that this weekend.

2021-04-27 22:40 UTC, talktocory commented
@JochenLinnemann - I've fixed the Azure pipeline build.  I need to add two different SDKs as Core and Function projects use 3.1 not 5.0.

`  - task: UseDotNet@2
    displayName: Install .NET Core 5.0 SDK
    inputs:    
      packageType: sdk
      version: 5.0.x
      includePreviewVersions: true
  - task: UseDotNet@2
    displayName: Install .NET Core 3.1 SDK
    inputs:
      packageType: sdk
      version: 3.1.x`

2021-05-07 12:01 UTC, JochenLinnemann approved these changes

2021-05-07 12:02 UTC, merged